spring:
  datasource:
    druid:
      driver-class-name: com.mysql.cj.jdbc.Driver
      ##如果后端项目服务器和数据库服务器不在同一台主机上，则需要修改localhost为数据库服务器的主机ip地址
      url: jdbc:mysql://8.130.103.175:3306/fmmall?characterEncoding=utf-8
#      url: jdbc:mysql://localhost:3306/fmmall?characterEncoding=utf-8
      username: root
      password: admin123
  redis:
    host: 8.130.103.175
    port: 6379
    password: 123456
    database: 0

mybatis:
  mapper-locations: classpath:mappers/*Mapper.xml
  type-aliases-package: com.qfedu.fmmall.entity